// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetLogInfo() {
  return window['go']['main']['App']['GetLogInfo']();
}

export function GetPoolInfo(arg1, arg2) {
  return window['go']['main']['App']['GetPoolInfo'](arg1, arg2);
}

export function GetUserList() {
  return window['go']['main']['App']['GetUserList']();
}

export function HandleCommunityTasks() {
  return window['go']['main']['App']['HandleCommunityTasks']();
}

export function IncrementalUpdatePoolInfo() {
  return window['go']['main']['App']['IncrementalUpdatePoolInfo']();
}

export function MergeEreRecord(arg1, arg2) {
  return window['go']['main']['App']['MergeEreRecord'](arg1, arg2);
}
