// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameInfo() {
  return window['go']['main']['App']['GetGameInfo']();
}

export function GetPoolInfo(arg1, arg2) {
  return window['go']['main']['App']['GetPoolInfo'](arg1, arg2);
}

export function GetUserList() {
  return window['go']['main']['App']['GetUserList']();
}

export function IncrementalUpdatePoolInfo() {
  return window['go']['main']['App']['IncrementalUpdatePoolInfo']();
}
