// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureClose() {
  return window['go']['main']['App']['CaptureClose']();
}

export function CaptureStart() {
  return window['go']['main']['App']['CaptureStart']();
}

export function ExportMccExcel(arg1) {
  return window['go']['main']['App']['ExportMccExcel'](arg1);
}

export function ExportRawJson(arg1) {
  return window['go']['main']['App']['ExportRawJson'](arg1);
}

export function GetCommunityExchangeList() {
  return window['go']['main']['App']['GetCommunityExchangeList']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetLogInfo() {
  return window['go']['main']['App']['GetLogInfo']();
}

export function GetPoolInfo(arg1, arg2) {
  return window['go']['main']['App']['GetPoolInfo'](arg1, arg2);
}

export function GetSettingCapturePort() {
  return window['go']['main']['App']['GetSettingCapturePort']();
}

export function GetSettingExchangeList() {
  return window['go']['main']['App']['GetSettingExchangeList']();
}

export function GetSettingFont() {
  return window['go']['main']['App']['GetSettingFont']();
}

export function GetSettingLayout() {
  return window['go']['main']['App']['GetSettingLayout']();
}

export function GetUserList() {
  return window['go']['main']['App']['GetUserList']();
}

export function HandleCommunityTasks() {
  return window['go']['main']['App']['HandleCommunityTasks']();
}

export function ImportMccExcel(arg1) {
  return window['go']['main']['App']['ImportMccExcel'](arg1);
}

export function ImportRawJson(arg1, arg2) {
  return window['go']['main']['App']['ImportRawJson'](arg1, arg2);
}

export function MergeEreRecord(arg1, arg2) {
  return window['go']['main']['App']['MergeEreRecord'](arg1, arg2);
}

export function SaveSettingCapturePort(arg1) {
  return window['go']['main']['App']['SaveSettingCapturePort'](arg1);
}

export function SaveSettingExchangeList(arg1) {
  return window['go']['main']['App']['SaveSettingExchangeList'](arg1);
}

export function SaveSettingFont(arg1) {
  return window['go']['main']['App']['SaveSettingFont'](arg1);
}

export function SaveSettingLayout(arg1) {
  return window['go']['main']['App']['SaveSettingLayout'](arg1);
}

export function UpdatePoolInfo(arg1) {
  return window['go']['main']['App']['UpdatePoolInfo'](arg1);
}

export function UpdateTo(arg1) {
  return window['go']['main']['App']['UpdateTo'](arg1);
}
