// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CaptureClose():Promise<void>;

export function CaptureStart():Promise<void>;

export function ExportMccExcel(arg1:string):Promise<string>;

export function ExportRawJson(arg1:string):Promise<string>;

export function GetCommunityExchangeList():Promise<Array<model.CommunityExchangeList>>;

export function GetCurrentVersion():Promise<string>;

export function GetLatestVersion():Promise<string>;

export function GetLogInfo():Promise<model.LogInfo>;

export function GetPoolInfo(arg1:string,arg2:number):Promise<model.Pool>;

export function GetSettingCapturePort():Promise<number>;

export function GetSettingExchangeList():Promise<Array<number>>;

export function GetSettingFont():Promise<string>;

export function GetSettingLayout():Promise<number>;

export function GetUserList():Promise<Array<string>>;

export function HandleCommunityTasks():Promise<Array<string>>;

export function ImportMccExcel(arg1:string):Promise<string>;

export function ImportRawJson(arg1:string,arg2:boolean):Promise<string>;

export function MergeEreRecord(arg1:string,arg2:string):Promise<string>;

export function SaveSettingCapturePort(arg1:number):Promise<void>;

export function SaveSettingExchangeList(arg1:Array<number>):Promise<void>;

export function SaveSettingFont(arg1:string):Promise<void>;

export function SaveSettingLayout(arg1:number):Promise<void>;

export function UpdatePoolInfo(arg1:boolean):Promise<Array<string>>;

export function UpdateTo(arg1:string):Promise<string>;
